name: Publish to JSR

on:
  push:
    branches: [main]
    paths:
      - 'packages/*/jsr.json'
      - 'packages/*/src/**'
      - 'packages/typescript/*.json'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - packages/eslint
          - packages/typescript
          - packages/prettier
          - packages/commitlint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/publish/jsr
        working-directory: ${{ matrix.package }}
