name: Publish to JSR

on:
  push:
    branches: [main]
    paths:
      - 'packages/*/jsr.json'
      - 'packages/*/src/**'
      - 'packages/typescript/*.json'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    uses: ./.github/workflows/publish-jsr.yml
    with:
      packages: '["packages/eslint", "packages/typescript", "packages/prettier", "packages/commitlint"]'
